name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: albumify-staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Unit Tests
      run: dotnet test --filter FullyQualifiedName~UnitTests
    - name: Integration Tests
      env:
        SpotifyClientId: ${{ secrets.SpotifyClientId }}
        SpotifyClientSecret: ${{ secrets.SpotifyClientSecret }}
      run: dotnet test --filter FullyQualifiedName~IntegrationTests
    - name: dotnet publish
      run: dotnet publish Albumify.Web --configuration Release -o 'published-app'
    - name: Deploy to Azure Web Apps using publish profile creds
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AzureWebAppPublishProfile }}
        package: published-app
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: 'published-app'
        path: published-app